
graph TD
    subgraph "案1"
        subgraph "クライアント1"
            A2[クライアント]
        end
        
        subgraph "WTPサーバ1_1"
            E2[パケット生成・解釈プロセス
            - 座標解決リクエストなら座標解決サーバにリクエスト
            - リクエストならクエリ組み立てプロセスに渡す]
            B2[座標解決サーバ]
        end
        
        subgraph "WTPサーバ1_2"
            C2[クエリ組み立てプロセス]
            D2[Redis]
        end
        
        A2 -->|"リクエスト
        or
        座標解決リクエスト
        S1 UDP/4110"| E2
        E2 -->|"レスポンス
        R1 UDP"| A2
        
        A2 -->|"座標解決リクエスト
        S0 UDP/4109"| B2
        B2 -->|"座標解決レスポンス
        R0 UDP"| A2
        
        E2 -->|"座標解決リクエスト
        S2 UDP/4109"| B2
        B2 -->|"座標解決レスポンス
        R2 UDP"| E2
        
        E2 -->|"リクエスト
        S3 UDP "| C2
        C2 -->|"レスポンス
        R3 UDP"| E2
        C2 -->|"クエリ
        S4 TCP"| D2
        D2 -->|"気象情報
        R4 TCP"| C2
    end