---
config:
  layout: fixed
  theme: neo-dark
  look: neo
---
flowchart LR
 subgraph Client["クライアント1"]
        A2["クライアント"]
  end
 subgraph Server1["WTPサーバ1_1"]
        E2["パケット生成・解釈プロセス<br>- 座標解決リクエストなら座標解決サーバにリクエスト<br>- リクエストならクエリ組み立てプロセスに渡す"]
        B2["座標解決サーバ"]
  end
 subgraph Server2["WTPサーバ1_2"]
        C2["クエリ組み立てプロセス"]
        D2["Redis"]
  end
    A2 -- リクエスト<br>または座標解決リクエスト<br>S1 UDP/4110 --> E2
    A2 -- 座標解決リクエスト<br>S0 UDP/4109 --> B2
    E2 -- レスポンス<br>R1 UDP --> A2
    B2 -- 座標解決レスポンス<br>R0 UDP --> A2
    E2 -- 座標解決リクエスト<br>S2 UDP/4109 --> B2
    B2 -- 座標解決レスポンス<br>R2 UDP --> E2
    E2 -- リクエスト<br>S3 UDP --> C2
    C2 -- レスポンス<br>R3 UDP --> E2
    C2 -- クエリ<br>S4 TCP --> D2
    D2 -- 気象情報<br>R4 TCP --> C2
