[package]
name = "wip_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bitvec = "1.0"
serde_json = "1.0"

[[example]]
name = "client"
path = "examples/client.rs"
test = false

[[example]]
name = "structured_client"
path = "examples/structured_client.rs"
test = false
