name: Build C++ Components

on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp-build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential catch2 libssl-dev
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install -y cmake
      - name: Configure
        run: |
          cmake -S cpp/wip -B build
      - name: Build
        run: |
          cmake --build build
      - name: Test
        run: |
          cd build
          ctest --output-on-failure
