name: Build C++ Components

on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp-build.yml'
  pull_request:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      - name: Configure
        run: |
          cmake -S cpp -B build
      - name: Build
        run: |
          cmake --build build
