name: Interop (no socket)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure (CMake)
        run: cmake -S cpp -B cpp/build -DCMAKE_BUILD_TYPE=Release

      - name: Build C++ tools
        run: cmake --build cpp/build --config Release --target wip_packet_gen wip_packet_decode

      - name: Run interop (no socket)
        env:
          WIP_CPP_BIN_DIR: cpp/build
          PYTHONPATH: src
        run: python python/tools/interop_no_socket.py

